### ISSUE TITLE
The .htaccess file does not work! Help me please!

### ISSUE THREAD

**Issue by matveyb9** [mayTermux/lampTermux#15]
Hello, dear developers! Thank you very much for your project lampTermux. Everything works except the .htaccess files. When running a project with a .htaccess file, it is either ignored or a 500 error is displayed. Help me please! Thanks You!

**Comment by armandwipangestu** [comment]
What if you change Apache configuration to this on `httpd.conf` file?

- Load `rewrite_module` (uncomment to load the module)

```conf
LoadModule rewrite_module libexec/apache2/mod_rewrite.so
```

- Enable `AllowOverride All` to `htdocs` PATH

```conf
DocumentRoot "/data/data/com.termux/files/home/htdocs"
<Directory "/data/data/com.termux/files/home/htdocs">
    ...
    AllowOverride All
    Require all granted
</Directory>
```

Then you can try to restart the service apache

**Comment by matveybaranov09** [comment]
Thank you very much. You helped me a lot.

**Comment by matveyb9** [comment]
Thank you very much. You helped me a lot!
